/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.BarangController;
import controller.PemasokController;
import java.sql.Connection;
import java.util.List;

/**
 *
 * @author budiarti
 */
public class BarangView extends javax.swing.JInternalFrame {

    private final ViewProccess viewProccess;
    private final BarangController barangController;
    private final String[] header = {"Barang Id", "Nama Barang", "Stok Barang", "Harga Barang", "Nama Pemasok"};
    private final String[] category = {"barang_id", "nama_barang", "stok_barang", "harga_barang", "nama_pemasok"};
    private final Connection connection;
    private final List<Object[]> PemasokTemp;

    /**
     * Creates new form Master
     */
    public BarangView(Connection connection) {
        this.connection = connection;
        initComponents();
        this.viewProccess = new ViewProccess();
        this.barangController = new BarangController(connection);
        this.PemasokTemp = this.getDataPemasok();
        this.loadSearchComboBox();
        this.loadPemasok();
        this.reset();
        this.bindingTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findcomboBarang = new javax.swing.JComboBox<String>();
        findtxtfieldBarang = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idtxtfieldBarang = new javax.swing.JTextField();
        nametxtfieldBarang = new javax.swing.JTextField();
        stoktxtfieldBarang = new javax.swing.JTextField();
        hargatxtfieldBarang = new javax.swing.JTextField();
        dropbtnBarang = new javax.swing.JButton();
        savebtnBarang = new javax.swing.JButton();
        idcomboPemasok = new javax.swing.JComboBox<String>();
        btnFind = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Barang");

        findcomboBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findcomboBarangActionPerformed(evt);
            }
        });

        findtxtfieldBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                findtxtfieldBarangKeyPressed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));

        jLabel1.setText("Barang ID");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Stok Barang");

        jLabel4.setText("Harga Barang");

        jLabel5.setText("Nama Pemasok");

        dropbtnBarang.setText("Drop");
        dropbtnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropbtnBarangActionPerformed(evt);
            }
        });

        savebtnBarang.setText("Save");
        savebtnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnBarangActionPerformed(evt);
            }
        });

        idcomboPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcomboPemasokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nametxtfieldBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxtfieldBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dropbtnBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(savebtnBarang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hargatxtfieldBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(stoktxtfieldBarang)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(idcomboPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idtxtfieldBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stoktxtfieldBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nametxtfieldBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(hargatxtfieldBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idcomboPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropbtnBarang)
                    .addComponent(savebtnBarang))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(findcomboBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findtxtfieldBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btnFind)
                .addGap(38, 38, 38))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findcomboBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findtxtfieldBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        this.search(this.viewProccess.getCategory(this.category, findcomboBarang), findtxtfieldBarang.getText());
    }//GEN-LAST:event_btnFindActionPerformed

    private void findtxtfieldBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findtxtfieldBarangKeyPressed
        if (this.viewProccess.keyPressed(evt)) {
            this.search(this.viewProccess.getCategory(this.category, findcomboBarang), findtxtfieldBarang.getText());
        }
    }//GEN-LAST:event_findtxtfieldBarangKeyPressed

    private void savebtnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnBarangActionPerformed
        this.saveOrEdit(idtxtfieldBarang.getText(), nametxtfieldBarang.getText(),
                Integer.parseInt(stoktxtfieldBarang.getText()), Integer.parseInt(hargatxtfieldBarang.getText()),
                idcomboPemasok.getSelectedIndex(), idtxtfieldBarang.isEnabled());
    }//GEN-LAST:event_savebtnBarangActionPerformed

    private void dropbtnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropbtnBarangActionPerformed
        this.drop(idtxtfieldBarang.getText());
    }//GEN-LAST:event_dropbtnBarangActionPerformed

    private void findcomboBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findcomboBarangActionPerformed
        this.search(this.viewProccess.getCategory(this.category, findcomboBarang), findtxtfieldBarang.getText());
    }//GEN-LAST:event_findcomboBarangActionPerformed

    private void idcomboPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcomboPemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcomboPemasokActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        this.mouseClick(tblBarang.getSelectedRow());
    }//GEN-LAST:event_tblBarangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton dropbtnBarang;
    private javax.swing.JComboBox<String> findcomboBarang;
    private javax.swing.JTextField findtxtfieldBarang;
    private javax.swing.JTextField hargatxtfieldBarang;
    private javax.swing.JComboBox<String> idcomboPemasok;
    private javax.swing.JTextField idtxtfieldBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nametxtfieldBarang;
    private javax.swing.JButton savebtnBarang;
    private javax.swing.JTextField stoktxtfieldBarang;
    private javax.swing.JTable tblBarang;
    // End of variables declaration//GEN-END:variables

    private void bindingTable() {
        this.viewProccess.viewTable(tblBarang, header,
                this.barangController.bindingSort(category[0], "asc"));
    }

    public void search(String category, String data) {
        this.viewProccess.viewTable(tblBarang, header, this.barangController.find(category, data));
    }

    private void loadSearchComboBox() {
        this.viewProccess.loadSearchComboBox(findcomboBarang, header);
    }

    private List<Object[]> getDataPemasok() {
        return new PemasokController(connection).bindingSort("pemasok_id", "asc");
    }

    private void loadPemasok() {
        this.viewProccess.loadDetails(idcomboPemasok, this.getDataPemasok(), 1);
    }

    private String getPemasokId() {
        return this.viewProccess.getIdfromComboBox(this.PemasokTemp, idcomboPemasok.getSelectedIndex());
    }

    public void drop(String barangId) {
        if (this.viewProccess.dropConfirm(this)) {
            this.viewProccess.dropData(this, this.barangController.drop(barangId));
        }
        this.reset();
    }

    public void saveOrEdit(String barangId, String barangNama, int stok, int harga, int pemasok, boolean isSave) {
        boolean flag = true;
        if (isSave) {
            flag = this.barangController.save(barangId, barangNama,
                    Integer.toString(stok), Integer.toString(harga), this.getPemasokId());
        } else {
            flag = this.barangController.edit(barangId, barangNama,
                    Integer.toString(stok), Integer.toString(harga), this.getPemasokId());
        }
        this.viewProccess.saveData(this, flag, isSave);
        this.reset();
    }

    public void mouseClick(int row) {
        idtxtfieldBarang.setEnabled(false);
        dropbtnBarang.setEnabled(true);
        idtxtfieldBarang.setText(tblBarang.getValueAt(row, 0).toString());
        nametxtfieldBarang.setText(tblBarang.getValueAt(row, 1).toString());
        stoktxtfieldBarang.setText(tblBarang.getValueAt(row, 2).toString());
        hargatxtfieldBarang.setText(tblBarang.getValueAt(row, 3).toString());
        idcomboPemasok.setSelectedItem(tblBarang.getValueAt(row, 4).toString());
    }

    /**
     * funsi reset komponen
     */
    public void reset() {
        idtxtfieldBarang.setEnabled(true);
        idtxtfieldBarang.setText("");
        nametxtfieldBarang.setText("");
        idcomboPemasok.setSelectedItem("");
        findtxtfieldBarang.setText("");
        stoktxtfieldBarang.setText("");
        hargatxtfieldBarang.setText("");
        this.bindingTable();
        dropbtnBarang.setEnabled(false);
    }
}
