/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.BarangController;
import controller.DetailBarangController;
import controller.TransaksiController;
import java.sql.Connection;
import java.util.List;

/**
 *
 * @author budiarti
 */
public class DetailTransaksiBarangView extends javax.swing.JInternalFrame {
    
    private final ViewProccess viewProccess;
    private final DetailBarangController detailBarangController;
    private final String[] header = {"Id", "Nama Pelanggan", "Nama Pegawai", "Nama Barang","Tanggal", "Jumlah Beli","Total Bayar" };
    private final String[] category = {"detail_barang_id", "nama_pegawai", "nama_pelanggan","nama_barang","tanggal", "jumlah_beli","total_bayar"};
    private final List<Object[]> TransTemp;
    private final List<Object[]> BarangTemp;
    private final Connection connection;

    /**
     * Creates new form DetailTransaksiBarangView
     */
    public DetailTransaksiBarangView(Connection connection) {
        this.connection=connection;
        initComponents();
        this.viewProccess = new ViewProccess();
        this.detailBarangController= new DetailBarangController(connection);
        this.TransTemp = this.getDataTrans();
        this.BarangTemp=this.getDataBarang();
        this.loadSearchComboBox();
        this.loadBarang();
        this.loadTrans();
        this.reset();
        this.bindingTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfieldJmlhBeli = new javax.swing.JTextField();
        idcomboBarang = new javax.swing.JComboBox<String>();
        idcomboTransaksi = new javax.swing.JComboBox<String>();
        savebtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        findcomboTransaksibarang = new javax.swing.JComboBox<String>();
        txtfieldFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetailBarang = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Detail Transaksi Barang");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Transaksi Barang"));

        jLabel1.setText("Jumlah Jual");

        jLabel2.setText("Barang ID");

        jLabel3.setText("Transaksi ID");

        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfieldJmlhBeli, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(id))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idcomboBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idcomboTransaksi, 0, 135, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(savebtn)
                .addGap(232, 232, 232))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtfieldJmlhBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idcomboBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(idcomboTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(savebtn)
                .addGap(44, 44, 44))
        );

        findcomboTransaksibarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findcomboTransaksibarangActionPerformed(evt);
            }
        });

        txtfieldFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfieldFindKeyPressed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        tblDetailBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDetailBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetailBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDetailBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(findcomboTransaksibarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfieldFind, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFind)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findcomboTransaksibarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfieldFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findcomboTransaksibarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findcomboTransaksibarangActionPerformed
       this.search(this.viewProccess.getCategory(this.category, findcomboTransaksibarang), txtfieldFind.getText());
    }//GEN-LAST:event_findcomboTransaksibarangActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        this.viewProccess.saveData(this, this.detailBarangController.save(id.getText(), this.getBarangId(),Integer.parseInt(txtfieldJmlhBeli.getText()), this.getTrans()), true);
    }//GEN-LAST:event_savebtnActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        this.search(this.viewProccess.getCategory(this.category, findcomboTransaksibarang), txtfieldFind.getText());
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtfieldFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfieldFindKeyPressed
        if (this.viewProccess.keyPressed(evt)) {
            this.search(this.viewProccess.getCategory(this.category, findcomboTransaksibarang), txtfieldFind.getText());
        }
    }//GEN-LAST:event_txtfieldFindKeyPressed

    private void tblDetailBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetailBarangMouseClicked
        this.mouseClick(tblDetailBarang.getSelectedRow());
    }//GEN-LAST:event_tblDetailBarangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JComboBox<String> findcomboTransaksibarang;
    private javax.swing.JTextField id;
    private javax.swing.JComboBox<String> idcomboBarang;
    private javax.swing.JComboBox<String> idcomboTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton savebtn;
    private javax.swing.JTable tblDetailBarang;
    private javax.swing.JTextField txtfieldFind;
    private javax.swing.JTextField txtfieldJmlhBeli;
    // End of variables declaration//GEN-END:variables


    private void bindingTable() {
        this.viewProccess.viewTable(tblDetailBarang, header,
                this.detailBarangController.bindingSort(category[0], "asc"));
    }

    public void search(String category, String data) {
        this.viewProccess.viewTable(tblDetailBarang, header, this.detailBarangController.find(category, data));
    }
    
    private void loadSearchComboBox() {
        this.viewProccess.loadSearchComboBox(findcomboTransaksibarang, header);
    }
    
    private List<Object[]> getDataBarang() {
        return new BarangController(connection).bindingSort("barang_id", "asc");
    }

    private void loadBarang() {
        this.viewProccess.loadDetails(idcomboBarang, this.getDataBarang(), 1);
    }

    private String getBarangId() {
        return this.viewProccess.getIdfromComboBox(this.BarangTemp, idcomboBarang.getSelectedIndex());
    }

    private List<Object[]> getDataTrans() {
        return new TransaksiController(connection).bindingSort("transaksi_id", "asc");
    }
    private void loadTrans() {
        this.viewProccess.loadDetails(idcomboTransaksi, this.getDataTrans(),0);
    }

    private String getTrans() {
        return this.viewProccess.getIdfromComboBox(this.TransTemp, idcomboTransaksi.getSelectedIndex());
    }

    public void mouseClick(int row) {
        id.setText(tblDetailBarang.getValueAt(row, 1).toString());
        idcomboBarang.setSelectedItem(tblDetailBarang.getValueAt(row, 2).toString());
        idcomboTransaksi.setSelectedItem(tblDetailBarang.getValueAt(row, 3).toString());
        txtfieldJmlhBeli.setText(tblDetailBarang.getValueAt(row, 4).toString());
    }

    /**
     * funsi reset komponen
     */
    public void reset() {
        idcomboBarang.setSelectedItem("");
        idcomboTransaksi.setSelectedItem("");
        txtfieldFind.setText("");
        this.bindingTable();
    }
}
