/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.BarangController;
import controller.DetailBarangController;
import controller.TransaksiController;
import java.sql.Connection;
import java.util.List;

/**
 *
 * @author budiarti
 */
public class DetailTransaksiBarangView extends javax.swing.JInternalFrame {
    
    private final ViewProccess viewProccess;
    private final DetailBarangController detailBarangController;
    private final String[] header = {"Id", "Nama Pelanggan", "Nama Pegawai", "Nama Barang","Tanggal", "Jumlah Beli","Total Bayar" };
    private final String[] category = {"detail_barang_id", "nama_pegawai", "nama_pegawai","nama_barang","tanggal", "jumlah_beli","total_bayar"};
    private final List<Object[]> TransTemp;
    private final List<Object[]> BarangTemp;
    private final Connection connection;

    /**
     * Creates new form DetailTransaksiBarangView
     */
    public DetailTransaksiBarangView(Connection connection) {
        this.connection=connection;
        initComponents();
        this.viewProccess = new ViewProccess();
        this.detailBarangController= new DetailBarangController(connection);
        this.TransTemp = this.getDataTrans();
        this.BarangTemp=this.getDataBarang();
        this.loadSearchComboBox();
        this.loadBarang();
        this.loadTrans();
        this.reset();
        this.bindingTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfieldJmlhBeli = new javax.swing.JTextField();
        idcomboBarang = new javax.swing.JComboBox<String>();
        idcomboTransaksi = new javax.swing.JComboBox<String>();
        dropbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        findcomboTransaksibarang = new javax.swing.JComboBox<String>();
        txtfieldFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetailBarang = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Detail Transaksi Barang");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Transaksi Barang"));

        jLabel1.setText("Jumlah Jual");

        jLabel2.setText("Barang ID");

        jLabel3.setText("Transaksi ID");

        dropbtn.setText("Drop");

        savebtn.setText("Save");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dropbtn)
                        .addGap(18, 18, 18)
                        .addComponent(savebtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfieldJmlhBeli, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(idcomboBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idcomboTransaksi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfieldJmlhBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idcomboBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idcomboTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropbtn)
                    .addComponent(savebtn)))
        );

        findcomboTransaksibarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findcomboTransaksibarangActionPerformed(evt);
            }
        });

        btnFind.setText("Find");

        tblDetailBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblDetailBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(findcomboTransaksibarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfieldFind, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFind)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findcomboTransaksibarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfieldFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findcomboTransaksibarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findcomboTransaksibarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findcomboTransaksibarangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton dropbtn;
    private javax.swing.JComboBox<String> findcomboTransaksibarang;
    private javax.swing.JComboBox<String> idcomboBarang;
    private javax.swing.JComboBox<String> idcomboTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton savebtn;
    private javax.swing.JTable tblDetailBarang;
    private javax.swing.JTextField txtfieldFind;
    private javax.swing.JTextField txtfieldJmlhBeli;
    // End of variables declaration//GEN-END:variables


    private void bindingTable() {
        this.viewProccess.viewTable(tblDetailBarang, header,
                this.detailBarangController.bindingSort(category[0], "asc"));
    }

    public void search(String category, String data) {
        this.viewProccess.viewTable(tblDetailBarang, header, this.detailBarangController.find(category, data));
    }
    
    private void loadSearchComboBox() {
        this.viewProccess.loadSearchComboBox(findcomboTransaksibarang, header);
    }
    
    private List<Object[]> getDataBarang() {
        return new BarangController(connection).bindingSort("barang_id", "asc");
    }

    private void loadBarang() {
        this.viewProccess.loadDetails(idcomboBarang, this.getDataBarang(), 1);
    }

    private String getBarangId() {
        return this.viewProccess.getIdfromComboBox(this.BarangTemp, idcomboBarang.getSelectedIndex());
    }

    private List<Object[]> getDataTrans() {
        return new TransaksiController(connection).bindingSort("transaksi_id", "asc");
    }
    private void loadTrans() {
        this.viewProccess.loadDetails(idcomboTransaksi, this.getDataTrans(),0);
    }

    private String getTrans() {
        return this.viewProccess.getIdfromComboBox(this.TransTemp, idcomboTransaksi.getSelectedIndex());
    }
    
     public void drop(String barangId) {
        if (this.viewProccess.dropConfirm(this)) {
            this.viewProccess.dropData(this, this.detailBarangController.drop(barangId));
        }
        this.reset();
    }

    public void saveOrEdit(String serviceId, int biaya, String serviceNama, boolean isSave) {
        boolean flag = true;
        if (isSave) {
           // flag = this.detailBarangController.save();
        } else {
          //  flag = this.detailBarangController.edit();
        }
        this.viewProccess.saveData(this, flag, isSave);
        this.reset();
    }

    public void mouseClick(int row) {
       // idtxtfieldService.setEnabled(false);
        dropbtn.setEnabled(true);
        //idtxtfieldService.setText(tblService.getValueAt(row, 0).toString());
        idcomboBarang.setSelectedItem(tblDetailBarang.getValueAt(row, 1).toString());
        idcomboTransaksi.setSelectedItem(tblDetailBarang.getValueAt(row, 2).toString());
        txtfieldJmlhBeli.setText(tblDetailBarang.getValueAt(row, 3).toString());
    }

    /**
     * funsi reset komponen
     */
    public void reset() {
        //idtxtfieldService.setEnabled(true);
        idcomboBarang.setSelectedItem("");
        idcomboTransaksi.setSelectedItem("");
        txtfieldFind.setText("");
        this.bindingTable();
        dropbtn.setEnabled(false);
    }
}
