/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.PeranController;
import java.sql.Connection;

/**
 *
 * @author budiarti
 */
public class PeranView extends javax.swing.JInternalFrame {
    
    private final ViewProccess viewProccess;
    private final PeranController peranController;
    private final String[] header = {"Peran Id", "Nama Peran"};
    private final String[] category = {"peran_id", "nama_peran"};
    private final Connection connection;

    /**
     * Creates new form PeranView
     */
    public PeranView(Connection connection) {
        this.connection=connection;
        initComponents();
        this.viewProccess = new ViewProccess();
        this.peranController = new PeranController(connection);        
        this.loadSearchComboBox();
        this.reset();
        this.bindingTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idtxtfieldPeran = new javax.swing.JTextField();
        namatxtfieldPeran = new javax.swing.JTextField();
        dropbtnPeran = new javax.swing.JButton();
        savebtnPeran = new javax.swing.JButton();
        findcomboPeran = new javax.swing.JComboBox<String>();
        findtxtfieldPeran = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPeran = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Peran");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));

        jLabel1.setText("Peran ID");

        jLabel2.setText("Nama Peran");

        dropbtnPeran.setText("Drop");
        dropbtnPeran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropbtnPeranActionPerformed(evt);
            }
        });

        savebtnPeran.setText("Save");
        savebtnPeran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnPeranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namatxtfieldPeran, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxtfieldPeran, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dropbtnPeran)
                        .addGap(18, 18, 18)
                        .addComponent(savebtnPeran)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idtxtfieldPeran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namatxtfieldPeran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropbtnPeran)
                    .addComponent(savebtnPeran))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        findcomboPeran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findcomboPeranActionPerformed(evt);
            }
        });

        findtxtfieldPeran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                findtxtfieldPeranKeyPressed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        tblPeran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblPeran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeranMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPeran);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(findcomboPeran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(findtxtfieldPeran, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFind))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findcomboPeran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findtxtfieldPeran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnPeranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnPeranActionPerformed
        this.saveOrEdit(idtxtfieldPeran.getText(), namatxtfieldPeran.getText(),idtxtfieldPeran.isEnabled());
    }//GEN-LAST:event_savebtnPeranActionPerformed

    private void dropbtnPeranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropbtnPeranActionPerformed
        this.drop(idtxtfieldPeran.getText());
    }//GEN-LAST:event_dropbtnPeranActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        this.search(this.viewProccess.getCategory(this.category, findcomboPeran), findtxtfieldPeran.getText());
    }//GEN-LAST:event_btnFindActionPerformed

    private void findcomboPeranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findcomboPeranActionPerformed
        this.search(this.viewProccess.getCategory(this.category, findcomboPeran), findtxtfieldPeran.getText());
    }//GEN-LAST:event_findcomboPeranActionPerformed

    private void findtxtfieldPeranKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findtxtfieldPeranKeyPressed
        if (this.viewProccess.keyPressed(evt)) {
            this.search(this.viewProccess.getCategory(this.category, findcomboPeran), findtxtfieldPeran.getText());
    }    
    }//GEN-LAST:event_findtxtfieldPeranKeyPressed

    private void tblPeranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeranMouseClicked
        this.mouseClick(tblPeran.getSelectedRow());
    }//GEN-LAST:event_tblPeranMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton dropbtnPeran;
    private javax.swing.JComboBox<String> findcomboPeran;
    private javax.swing.JTextField findtxtfieldPeran;
    private javax.swing.JTextField idtxtfieldPeran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField namatxtfieldPeran;
    private javax.swing.JButton savebtnPeran;
    private javax.swing.JTable tblPeran;
    // End of variables declaration//GEN-END:variables


    private void bindingTable() {
        this.viewProccess.viewTable(tblPeran, header,
                this.peranController.bindingSort(category[0], "asc"));
    }

    public void search(String category, String data) {
        this.viewProccess.viewTable(tblPeran, header, this.peranController.find(category, data));
    }
    
    private void loadSearchComboBox() {
        this.viewProccess.loadSearchComboBox(findcomboPeran, header);
    }

     public void drop(String barangId) {
        if (this.viewProccess.dropConfirm(this)) {
            this.viewProccess.dropData(this, this.peranController.drop(barangId));
        }
        this.reset();
    }
     
    public void saveOrEdit(String peranId, String peranNama, boolean isSave) {
        boolean flag = true;
        if (isSave) {
            flag = this.peranController.save(idtxtfieldPeran.getText(), namatxtfieldPeran.getText());
        } else {
            flag = this.peranController.edit(idtxtfieldPeran.getText(), namatxtfieldPeran.getText());
        }
        this.viewProccess.saveData(this, flag, isSave);
        this.reset();
    }

    /**
     * fungsi menampilkan data yg yg telah diinputkan ke tbl country pada jframe
     *
     * @param row
     */
    public void mouseClick(int row) {
        idtxtfieldPeran.setEnabled(false);
        dropbtnPeran.setEnabled(true);
        idtxtfieldPeran.setText(tblPeran.getValueAt(row, 0).toString());
        namatxtfieldPeran.setText(tblPeran.getValueAt(row, 1).toString());
    }

    /**
     * funsi reset komponen
     */
    public void reset() {
        idtxtfieldPeran.setEnabled(true);
        namatxtfieldPeran.setText("");
        findtxtfieldPeran.setText("");
        this.bindingTable();
        dropbtnPeran.setEnabled(false);
    }
}
